### ISSUE TITLE
Support for SHA-512?

### ISSUE THREAD

**Issue by nnposter** [nccgroup/Decoder-Improved#13]
At the risk of missing something blatantly obvious, is there a reason why SHA-512 is not supported?

https://github.com/nccgroup/Decoder-Improved/blob/9bbba36f19688d39c26220b48f314b18559c0040/src/trust/nccgroup/decoderimproved/HashMode.java#L41

**Comment by justinmoore** [comment]
Hey @nnposter,

Maybe bouncy castle didn’t support SHA-512 at the time? There’s no real reason and I can add it as a feature when I get a chance.

Thanks,
Justin

**Comment by nnposter** [comment]
This would be great, as this is the only reason why I copy/paste data between DI and the built-in decoder. I have looked at the currently included BouncyCastle class files in the DI jar and SHA-512 seems to be there.

**Comment by justinmoore** [comment]
Hey @nnposter,

I've added this as a feature now. I'm closing this issue. Feel free to reopen it need be. 

Thanks,
Justin

**Comment by nnposter** [comment]
Perfect!
