### ISSUE TITLE
URL-decoding of the plus sign

### ISSUE THREAD

**Issue by nnposter** [nccgroup/Decoder-Improved#28]
Currently the plus sign (0x2B) is being passed through literally. In contrast, the built-in decoder will interpret it as a space character.

Decoder Improved:
`abc+-+def` --- (decode as URL) ---> `abc+-+def`

Decoder :
`abc+-+def` --- (decode as URL) ---> `abc - def`

I am proposing this change so Decoder Improved maintains compatibility with MIME type `application/x-www-form-urlencoded`.

https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1

**Comment by zehuanncc** [comment]
Hi @nnposter , thanks for finding the issue! This will be fixed very soon!
