### ISSUE TITLE
New tab with duplicate label

### ISSUE THREAD

**Issue by nnposter** [nccgroup/Decoder-Improved#30]
Decoder Improved generates new tab labels without checking for duplicates. Presumably this happens because the assigned integer label is derived from the count of existing tabs plus one.

Suggestion: When creating a new tab, keep incrementing the integer label until it becomes unique.

Steps to reproduce:
1. Open a few tabs
1. Close the first few tabs, keeping the last ones
1. Close and restart Burp
1. Observe that the tabs left after step 2 have been restored
1. Open a new tab, noting its duplicate label

### Seven tabs restored:
![DuplicateTabLabel-1-RestoredTabs](https://user-images.githubusercontent.com/10360850/69920533-9814fd00-1446-11ea-867a-a9d508760cda.png)

### New 8th tab:
![DuplicateTabLabel-2-NewTabLabel](https://user-images.githubusercontent.com/10360850/69920539-a105ce80-1446-11ea-9cf7-4419b609bc49.png)

**Comment by zehuanncc** [comment]
You're right, the current (first) number assigned to a new label is based on the count of tabs restored.

Your idea sounds great and I'll implement it. Thanks for the suggestion!
