### ISSUE TITLE
whitespace/newline on end breaks decoding

### ISSUE THREAD

**Issue by digininja** [nccgroup/Decoder-Improved#31]
I just asked it to decode the following as Base64:

```
YWFhCg==

```
The newline on the end caused the error "Invalid Base64 Input", the same happens if you have a space on the end. While the error may technically be true, but it would be annoying having to remember to trim excess whitespace.

It also fails with whitespace on the start, but that isn't quite as bad as a lot of things don't like leading whitespace.

**Comment by zehuanncc** [comment]
Thanks for finding the issue! Yes (at least trailing) spaces and newlines should be tolerated to make it easier to use. I'll make this change.
