### ISSUE TITLE
Incorrect automatic conversion to UTF-8

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/Decoder-Improved#4]
If a response containing some binary data (here a tar.gz archive) is sent to Decoder Improved, some characters are mangled and replaced by \xEF\xBF\xBD. This sequence is the UTF-8 value for the replacement character, used to "replace any incoming character whose value is unknown or un-representable".

As you can see in screenshots, the sequence "\x1F\x8B\x08" is converted to "\x1F\xEF\xBF\xBD\x08"
![di-1](https://user-images.githubusercontent.com/4039324/38319049-3063be1e-3831-11e8-8c5f-ce791d67e2db.png)
![di-2](https://user-images.githubusercontent.com/4039324/38319051-307ac9c4-3831-11e8-86e5-ee61d8f558bc.png)

More info:
https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD
https://blog.gdssecurity.com/labs/2015/2/18/when-efbfbd-and-friends-come-knocking-observations-of-byte-a.html

**Comment by zehuanncc** [comment]
Hi @ngregoire ,

Thanks for finding the bug!

This issue has been identified in the following code path:

The original byte array is captured from a request/response from the `createMenuItems()` [here](https://github.com/nccgroup/Decoder-Improved/blob/959338ab6b238d3b42a2c303d71a418835a93a53/src/trust/nccgroup/decoderimproved/SendToDecoderImprovedContextMenuFactory.java#L38) (and also in line 41, 53, 56).

The code above calls function `newUTF8String()` [here](https://github.com/nccgroup/Decoder-Improved/blob/959338ab6b238d3b42a2c303d71a418835a93a53/src/trust/nccgroup/decoderimproved/UTF8StringEncoder.java#L16). It uses `UTF-8` charset to convert byte arrays to strings, and replaces any unmappable character to the "replacement character". The output string (with mangled characters) will then be passed to the function `receiveTextFromMenu()` [here](https://github.com/nccgroup/Decoder-Improved/blob/959338ab6b238d3b42a2c303d71a418835a93a53/src/trust/nccgroup/decoderimproved/MultiDecoderTab.java#L111) and send to the tab.

A quick and straightforward fix of this issue will be sending the original byte arrays directly to the tab. However, it's still an issue for any processing based on the UTF-8 converted string. I'll do a thorough check on all the actions.
